### ISSUE TITLE
Socket gets fatal error and crashes the process 

### ISSUE THREAD

**Issue by carterharrison** [XYOracleNetwork/sdk-core-nodejs#196]
```info: Found nested block with hash: 1N9oNNBVFwGjqGzigp6RvjF25EpwQuXMvka6S4Rgn4nTdYp
info: Found nested block with hash: 1N9bPqqj8VQJuQ4FtCAN1y7h37wFT6cYpd3eyuYkPqhAnVA
info: Closing connection with ::ffff:70.66.216.58:5674
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.```

**Comment by carterharrison** [comment]
Fixed in https://github.com/XYOracleNetwork/sdk-core-nodejs/pull/197
